#! /usr/bin/env python3

# so as can then grep the mark and let grep provide context

import argparse, signal
signal.signal(signal.SIGINT, signal.SIG_DFL)
signal.signal(signal.SIGPIPE, signal.SIG_DFL)

parser = argparse.ArgumentParser(description = '''
    Mark wayward conj with -, to grep -C N ^-, in stdout.
''')
parser.add_argument('infile', nargs = '+',
                    type = argparse.FileType(encoding = 'UTF-8'),
                    help = 'input file (conllu)')
args = parser.parse_args()

def isbad(line, *, digits = tuple('123456789')):
    if not line.startswith(digits): return False
    record = line.rstrip('\n').split('\t')    
    return ( record[REL] == 'conj' and
             int(record[ID]) < int(record[HEAD]) )

ID, HEAD, REL = 0, 6, 7
for infile in args.infile:
    with infile as source:
        for line in source:
            print('-' if isbad(line) else '', line,
                  sep = '', end = '')
