#! /usr/bin/env python3
# -*- mode: Python; -*-

from argparse import ArgumentParser
import os, sys

def parseargs():
    description = '''

    Replace rel "advmod" with "nmod" when upos is "NOUN", with "dep"
    when upos is "X" and feat contains "Foreign=Yes". Leave a trace
    "Was18=advmod" in Misc.

    '''
    parser = ArgumentParser(description = description)

    parser.add_argument('inf',
                        help = '''
                        
                        input file in *.conllu

                        ''')
                        
    parser.add_argument('--in-place', '-i',
                        dest = 'inplace',
                        action = 'store_true',
                        help = '''

                        write to "{input-file}-temp" and replace input
                        file with output file at end
                        

                        ''')

    return parser.parse_args()

def main(args):

    if not args.inf.endswith('.conllu'):
        print('error: input file not in *.conllu:', args.inf,
              file = sys.stderr)
        exit(1)

    # used if args.inplace
    ouf = '{}-temp'.format(args.inf)

    # assumes sys.stdout is UTF-8 - please make it so
    out = (open(ouf, mode = 'w', encoding = 'UTF-8')
           if args.inplace
           else sys.stdout)

    for line in open(args.inf, encoding = 'UTF-8'):
        if not line[:1].isdigit():
            print(line, end = '', file = out)
            continue

        [ ref, word, base,
          upos, xpos,
          feat, head, rel,
          wev, misc ] = line.rstrip('\r\n').split('\t')

        trace = None
        if upos == 'NOUN' and rel == 'advmod':
            trace = 'Was18={}'.format(rel)
            rel = 'nmod'
        elif upos == 'X' and 'Foreign=Yes' in feat and rel == 'advmod':
            trace = 'Was18={}'.format(rel)
            rel = 'dep'

        if trace:
            # following is untested overkill for NOUN/advmod (always _)
            # ditto X[Foreign=Yes]/advmod
            misc = '|'.join(sorted(([] if misc == '_' else misc.split('|'))
                                   + [trace],
                                   key = str.lower))

        print(ref, word, base, upos, xpos, feat, head, rel, wev, misc,
              sep = '\t',
              file = out)

    if args.inplace:
        out.close()
        os.rename(args.inf, '{}~'.format(args.inf))
        os.rename(ouf, args.inf)

if __name__ == '__main__':
    try:
        main(parseargs())
    except BrokenPipeError as exn:
        print(exn)
    except KeyboardInterrupt as exn:
        print(exn)
